mortgage/urls.py
from django.contrib import admin
from django.urls import path
from calc.views import IndexView, InvestmentView, AboutView

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', IndexView.as_view()),
	path('stream/', InvestmentView.as_view()),
	path('about/', AboutView.as_view())
]

calc/models.py
from django.db import models

# Create your models here.

calc/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from decimal import Decimal

class InvestmentForm(forms.Form):
	
	FEDERAL_TAX_RATE = (
		('.1', ('10% - Income $9,525/$19,050 Single/Married')),
		('.12', ('12% - Income $38,700/$77,400 Single/Married')),
		('.22', ('22% - Income $82,500/$165,000 Single/Married')),
		('.24', ('24% - Income $157,500/$315,000 Single/Married')),
		('.32', ('32% - Income $200,000/$400,000 Single/Married')),
		('.35', ('35% - Income $500,000/$600,000 Single/Married')),
		('.37', ('37% - Income $500,000+/$600,000+ Single/Married')),
	)
	
	price = forms.IntegerField()
	closing_cost = forms.DecimalField(max_value=100, min_value=0, max_digits=4, decimal_places=2)
	maintenance_cost = forms.DecimalField(max_value=100, min_value=0, max_digits=4, decimal_places=2)
	property_tax = forms.DecimalField(max_value=100, min_value=0, max_digits=4, decimal_places=2)
	down_payment = forms.DecimalField(max_value=100, min_value=0, max_digits=5, decimal_places=2)
	interest_rate = forms.DecimalField(max_value=100, min_value=0, max_digits=4, decimal_places=2)
	yearly_appreciation = forms.DecimalField(max_value=100, min_value=0, max_digits=4, decimal_places=2)
	alternative_rent = forms.IntegerField(min_value=0)
	realtor_cost = forms.DecimalField(max_value=100, min_value=0, max_digits=4, decimal_places=2)
	federal_tax_bracket = forms.ChoiceField(choices=FEDERAL_TAX_RATE, initial=.24)
	state_tax_bracket = forms.DecimalField(max_value=100, min_value=0, max_digits=4, decimal_places=2)
	insurance = forms.DecimalField(max_value=100, min_value=0, max_digits=4, decimal_places=2)

	def clean_closing_cost(self):
		data = self.cleaned_data['closing_cost']
		return data / 100
	
	def clean_maintenance_cost(self):
		data = self.cleaned_data['maintenance_cost']
		return data / 100

	def clean_property_tax(self):
		data = self.cleaned_data['property_tax']
		return data / 100
	
	def clean_down_payment(self):
		data = self.cleaned_data['down_payment']
		return data / 100
	
	def clean_interest_rate(self):
		data = self.cleaned_data['interest_rate']
		return data / 100
	
	def clean_yearly_appreciation(self):
		data = self.cleaned_data['yearly_appreciation']
		return data / 100
	
	def clean_realtor_cost(self):
		data = self.cleaned_data['realtor_cost']
		return data / 100
	
	def clean_federal_tax_bracket(self):
		data = self.cleaned_data['federal_tax_bracket']
		return Decimal(data)
	
	def clean_state_tax_bracket(self):
		data = self.cleaned_data['state_tax_bracket']
		return data / 100
	
	def clean_insurance(self):
		data = self.cleaned_data['insurance']
		return data / 100

calc/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponse, JsonResponse
from calc.forms import InvestmentForm
from calc.house import House
from calc.mortgage import Mortgage
from calc.investment import Investment
from decimal import Decimal
import copy
from django.conf import settings

class AboutView(View):
	"""Return About and Methodology page."""
	
	template_name = 'calc/about.html'
	
	def get(self, request, *args, **kwargs):
		return render(request, self.template_name)

	
class IndexView(View): 
	"""Return home page."""
	
	template_name = 'calc/index.html'
	form_class = InvestmentForm
	
	def get(self, request, *args, **kwargs):
		"""Return rendered page with form pre-filled if params provided.
		
		Args:
			request (HttpRequest): Django request object including GET params 
				which, if provided, are used to pre-fill the form.
			
		Returns:
			HttpResponse: Rendered page.
		
		"""
			
		float_parameters = ['closing_cost', 'maintenance_cost', 'property_tax', 'down_payment', 'interest_rate', 'yearly_appreciation', 'realtor_cost', 'federal_tax_bracket', 'state_tax_bracket', 'insurance']
		
		context_dict = {}
		
		# Collects GET parameters from URL to add to pre-fill form fields
		for parameter in float_parameters:
			if parameter in request.GET:
				try:
					context_dict[parameter] = float(request.GET[parameter])
				except:
					pass
				
		int_parameters = ['price', 'alternative_rent']
		
		for parameter in int_parameters:
			if parameter in request.GET:
				try:
					context_dict[parameter] = int(request.GET[parameter])
				except:
					pass
		
		return render(request, self.template_name, context_dict)
	

class InvestmentView(View): 
	"""Endpoint returning dict of cash flows and IRRs."""
	
	# Dicts for modified values of each scenario
	no_leverage = {
		'yearly_interest_rate': 0,
		'down_payment_percent': 1,
		'name': 'mortgage_driver_irr'
	}

	no_alternative_rent = {
		'alternative_rent': 0,
		'name': 'alternative_rent_driver_irr'
	}

	no_tax_shield = {
		'state_tax_rate': 0,
		'federal_tax_rate': 0,
		'name': 'tax_shield_driver_irr'
	}

	no_appreciation = {
		'yearly_appreciation_rate': 0,
		'name': 'appreciation_driver_irr'
	}

	no_expenses = {
		'yearly_property_tax_rate': 0,
		'yearly_maintenance_as_percent_of_value': 0, 
		'insurance': 0,
		'closing_cost_as_percent_of_value': 0,
		'name': 'expenses_driver_irr'
	}

	other_scenarios = [
		no_leverage,
		no_alternative_rent,
		no_tax_shield,
		no_appreciation,
		no_expenses
	]
	
	@staticmethod
	def _build_investment(scenario):
		
		house = House(
			scenario['price'], 
			scenario['yearly_appreciation_rate'], 
			scenario['yearly_property_tax_rate'], 
			scenario['yearly_maintenance_as_percent_of_value'], 
			scenario['insurance']
		)
		
		mortgage = Mortgage(
			house, 
			scenario['yearly_interest_rate'], 
			settings.TERM_IN_YEARS, 
			scenario['down_payment_percent']
		)	
		
		investment = Investment(
			house, 
			mortgage, 
			scenario['closing_cost_as_percent_of_value'], 
			scenario['alternative_rent'], 
			scenario['realtor_cost'], 
			scenario['federal_tax_rate'], 
			scenario['state_tax_rate']
		)
		
		return investment
	
	@staticmethod
	def _get_unified_scenario(comprehensive_scenario, modified_scenario):
		unified_scenario = copy.deepcopy(comprehensive_scenario)
		unified_scenario.update(modified_scenario)
			
		return unified_scenario

	@staticmethod
	def _get_irr_delta(base_irr, alternative_irr):
		irr_delta = []
		for year in range(1, len(base_irr)):
			# Handles case where one of the IRRs is null due to no positive cash flows
			try:
				delta =  base_irr[year] - alternative_irr[year]
				irr_delta.append(round(delta,2))
			except TypeError:
				irr_delta.append(None)
		
		return irr_delta
		
	
	def get(self, request, *args, **kwargs):
		"""Return JSON object of base case cash flows and alternate case IRRs.
		
		Args:
			request (HttpRequest): Django request object including GET params 
				which are used to calculate return.
			
		Returns:
			JsonResponse: Dict containing IRRs, cash stream, and base yearly 
				mortgage payment
		
		"""
		
		form = InvestmentForm(request.GET)
		if form.is_valid():				
			
			standard_investment = {
				'price': form.cleaned_data['price'],
				'yearly_appreciation_rate': form.cleaned_data['yearly_appreciation'],
				'yearly_property_tax_rate': form.cleaned_data['property_tax'],
				'yearly_maintenance_as_percent_of_value': form.cleaned_data['maintenance_cost'],
				'insurance': form.cleaned_data['insurance'],
				'yearly_interest_rate': form.cleaned_data['interest_rate'],
				'down_payment_percent': form.cleaned_data['down_payment'],
				'closing_cost_as_percent_of_value': form.cleaned_data['closing_cost'],
				'alternative_rent': form.cleaned_data['alternative_rent'] * 12,
				'realtor_cost': form.cleaned_data['realtor_cost'],
				'federal_tax_rate': form.cleaned_data['federal_tax_bracket'],
				'state_tax_rate': form.cleaned_data['state_tax_bracket'],		
			}

			# Base stream
			investment = self._build_investment(standard_investment)
			base_irr, cash_stream = investment.get_yearly_cash_flows_and_irr()
			mortgage_payment = int(round(investment.mortgage.monthly_payment))
			context_dict = {
				'base_irr': base_irr,
				'cash_stream': cash_stream,
				'mortgage_payment': mortgage_payment
			}

			high_appreciation = {
				'yearly_appreciation_rate': standard_investment['yearly_appreciation_rate'] + Decimal(.01),
			}
			
			low_appreciation = {
				'yearly_appreciation_rate': standard_investment['yearly_appreciation_rate'] - Decimal(.01),
			}
			
			scenario = self._get_unified_scenario(standard_investment, high_appreciation)
			investment = self._build_investment(scenario)
			high_irr, _ = investment.get_yearly_cash_flows_and_irr()
			context_dict['high_irr'] = high_irr
			
			scenario = self._get_unified_scenario(standard_investment, low_appreciation)
			investment = self._build_investment(scenario)
			low_irr, _ = investment.get_yearly_cash_flows_and_irr()
			context_dict['low_irr'] = low_irr
			
			for scenario in self.other_scenarios:
				unified_scenario = self._get_unified_scenario(standard_investment, scenario)
				investment = self._build_investment(unified_scenario)
				scenario_irr, _ = investment.get_yearly_cash_flows_and_irr()
				irr_delta = self._get_irr_delta(base_irr, scenario_irr)
				context_dict[scenario['name']] = irr_delta
			
			return JsonResponse(context_dict)
		else:
			print(form.errors)
		
		return JsonResponse(form.errors, status=400)

calc/templates/calc/about-modal.html
<!-- Modal -->
<div class="modal fade" id="aboutModal" tabindex="-1" role="dialog" aria-labelledby="aboutModal" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
			</div>
			<div class="modal-body">
				<h4>About</h4>
				<p>If you've ever gotten into a conversation about when it makes sense to buy a home, you'll often run across a few 'common sense' maxims -- 'when you have a mortage you're paying yourself instead of your landlord,' 'buying is cheaper than renting,' and 'a home is a great investment.' Certainly, there are conditions where all of these are true. But, just as certainly, <i>there are conditions where none of these are true!</i></p>
				<p>The goal then is to help everyone from the prospective home buyer in making an informed purchase to the friends at a bar re-hasing the endless rent v. buy debate.</p>
				<p>If you have any suggestions, comments, or questions, feel free to shoot me a note at <a href="mailto:garrett@mortgageroi.com">garrett@mortgageroi.com</a></p>
				<p>Cheers,</p>
				<p>Garrett<br>
				<a href="https://www.linkedin.com/in/garrettedel/" target="_blank">LinkedIn</a></p>
				
				<h4>Methodology</h4>

				<h5>Introduction</h5>
				<p>Anyone who has bought and sold a house has two numbers ingrained in their mind: what they bought it for and what they sold it for. Those are important! But what about everything in between? The property taxes you pay, the tax breaks you get, the rent you don't have to pay, the interest you pay, the down payment, etc. all play an important role in understanding the returns. We'll walk through three components: </p>
				<ul>
					<li>Calculating Returns</li>
					<li>Buying and Selling</li>
					<li>Owning</li>
				</ul>

				<h4>Calculating Returns</h4>
					<p>In calculating the return on investment from buying a house, you can't just consider what you bought and sold it for, you can to consider the cash flows in between as well. The Mortgage ROI Calculator uses the Internal Rate of Return method to help us do that(if you really want to understand the nuts and bolts of it, check out the <a href="https://en.wikipedia.org/wiki/Internal_rate_of_return">Wikipedia page</a>).</p>

				<h4>Buying and Selling</h4>
				<p><b>Buying:</b> The cash outlay in buying is made up of two components: the down payment and the closing costs.</p>
				<ul>
					<p><b>Down payment: </b> The down payment represents the portion of the purchase that is funded with the buyer's cash, typically 20% of the home price. If lower than 20%, many banks require private mortgage insurance which we assume is 1% of the balance of the loan until the loan balance is less than 80% of the purchase price.</p>
					
					<p><b>Closing costs: </b>There are a host of fees that are charged when buying a house -- mortgage origination fees, underwriting fees, title insurance, etc. <a href="https://www.zillow.com/mortgage-learning/closing-costs/">Zillow</a> estimates that this can be 2-5% of the cost of the home. The mortgage calculator takes the % entered in the 'Closing Costs' field and multiplies it by the price of the home to create an all-in cash outlay in year 0 (i.e., the down payment plus closing costs.</p>
				</ul>
				<p><b>Selling:</b> Upon sale of the house, the homeowner gets the value of the house less the outstanding debt on the house and realtors' fees. Typically, realtors charge 6% of the value of the listing to the seller.</p>

				<h4>Owning</h4>
				<p>Just as important as the purchase price and costs, down payment, and sale price and costs are the cash flows that take place during home ownership. This model takes into account the following costs: </p>
				<ul>
					<p><b>Mortgage payment:</b> Principal and interest paid to the bank</p>
					<p><b>Property taxes:</b> Calculated on a yearly basis for simplicity</p>
					<p><b>Homeowner's insurance:</b> Assumed to be a percent of the <i>average value of the home</i> (i.e., last year's ending value + this year's ending value divided by 2)</p>
					<p><b>Maintenance:</b> Assumed to be a percent of the <i>average value of the home</i> (i.e., last year's ending value + this year's ending value divided by 2)</p>
					<p><b>Private mortgage insurance:</b> Assessed as 1% of the outstanding debt while the outstanding debt is greater than 80% of the original purchase price.</p>
					<p><b>Mortgage interest tax deduction:</b> Assumes you deduct the full amount of interest paid on both federal and state tax returns. With the latest tax laws, this is capped for mortgages that have greater than a $750,000 oustanding balance (i.e., if you have a $1M loan balance, you only deduct the interest paid on the first $750,000)</p>
					<p><b>State and local tax deduction:</b> Assumes you can deduct the lesser of the full amount of the property taxes you pay or $10,000 on your federal tax returns.</p>
					<p><b>Rent avoidance:</b> The rent you avoid paying by owning is assumed to grow at the same rate as the appreciation on your home.</p>
				</ul>

			</div>

			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
			</div>

		</div>
	</div>
</div>

calc/templates/calc/investment-form.html
<form id="investmentForm" method="get" action="/stream" novalidate>
<div class="row">
	<div class="col-md-4">
		<div class="form-group row">
			<label for="id_price" class="col-md-5 col-form-label">Price</label>
			<div class="col-md-7">
				<input type="text" name="price" class="form-control" aria-expanded="false" required id="id_price" value={% if price %}{{ price }}{% else %}"500,000"{% endif %}>
			</div>
			<div class="col-md-12">
				<div class="collapse" id="price-collapse" name="price">
					<div class="card card-body">
						<p>Total price of the home in dollars, <i>excluding closing costs, appraisals, etc.</i></p>
					</div>
				</div>
			</div>
		</div>

		<div class="form-group row">
			<label for="id_down_payment" class="col-md-5 col-form-label">Down payment</label>
			<div class="col-md-7">
				<div class="input-group">
					<input type="number" name="down_payment" min="0" max="100" step="0.01" class="form-control" required id="id_down_payment" value={% if down_payment %}{{ down_payment }}{% else %}"20.0"{% endif %}>
					<div class="input-group-append">
						<span class="input-group-text">%</span>
					</div>
				</div>
			</div>
			<div class="col-md-12">
				<div class="collapse" id="price-collapse" name="down_payment">
					<div class="card card-body">
						<p>Down payment percent of the purchase price. <b>If less than 20%, requires PMI insurance of 1% of the loan balance until you hit 20% principal paid</b>. If the appreciation of the home is greater than the interest rate, a lower down payment increases the investment returns.</p>
					</div>
				</div>
			</div>
		</div>

		<div class="form-group row">
			<label for="id_interest_rate" class="col-md-5 col-form-label">Interest rate</label>
			<div class="col-md-7">
				<div class="input-group">
					<input type="number" name="interest_rate" min="0" max="100" step="0.01" class="form-control" required id="id_interest_rate" value={% if interest_rate %}{{ interest_rate }}{% else %}"5.0"{% endif %}>
					<div class="input-group-append">
						<span class="input-group-text">%</span>
					</div>
				</div>
			</div>
			<div class="col-md-12">
				<div class="collapse" id="price-collapse" name="interest_rate">
					<div class="card card-body">
						<p>The mortgage rate is best thought of as the cost of 'renting' the money that you are borrowing. The higher the interest rate, the greater the loan payment each month and the lower the returns.</p>
					</div>
				</div>
			</div>
		</div>

		<div class="form-group row">
			<label for="id_yearly_appreciation" class="col-md-5 col-form-label">Yearly appreciation</label>
			<div class="col-md-7">
				<div class="input-group">
					<input type="number" name="yearly_appreciation" min="0" max="100" step="0.01" class="form-control" required id="id_yearly_appreciation" value={% if yearly_appreciation %}{{ yearly_appreciation }}{% else %}"5.0"{% endif %}>
					<div class="input-group-append">
						<span class="input-group-text">%</span>
					</div>
				</div>
			</div>
			<div class="col-md-12">
				<div class="collapse" id="price-collapse" name="yearly_appreciation">
					<div class="card card-body">
						<p>Yearly value appreciation - Sustaining <i>long-term</i> yearly appreciation over 5% is historically unlikely (see below).</p>
						<p><b>Annualized returns to Dec 2017 by purchase year</b></p>
						{% include "calc/appreciation-table.html" %}
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="col-md-4">

		<div class="form-group row">
			<label for="id_alternative_rent" class="col-md-5 col-form-label">Monthly rent</label>
			<div class="col-md-7">
				<input type="text" lang="en-150" name="alternative_rent" class="form-control" required id="id_alternative_rent" value={% if alternative_rent %}{{ alternative_rent }}{% else %}"1,500"{% endif %}>
			</div>
			<div class="col-md-12">
				<div class="collapse" id="price-collapse" name="alternative_rent">
					<div class="card card-body">
						<p><b>Monthly</b> rent you would pay if you do not buy -- your current rent is a good proxy.</p>
					</div>
				</div>
			</div>
		</div>

		<div class="form-group row">
			<label for="id_price" class="col-md-5 col-form-label">Federal tax rate</label>
			<div class="col-md-7">
				<select name="federal_tax_bracket" id="id_federal_tax_bracket" class="form-control" aria-expanded="false">
			  <option value=".1" {% if federal_tax_bracket == .1 %}selected{% endif %}>10% - Income $9,525/$19,050 Single/Married</option>
			  <option value=".12" {% if federal_tax_bracket == .12 %}selected{% endif %}>12% - Income $38,700/$77,400 Single/Married</option>
			  <option value=".22" {% if federal_tax_bracket == .22 %}selected{% endif %}>22% - Income $82,500/$165,000 Single/Married</option>
			  <option value=".24" {% if federal_tax_bracket == .24 %}selected{% endif %} {% if not federal_tax_bracket %}selected{% endif %}>24% - Income $157,500/$315,000 Single/Married</option>
			  <option value=".32" {% if federal_tax_bracket == .32 %}selected{% endif %}>32% - Income $200,000/$400,000 Single/Married</option>
			  <option value=".35" {% if federal_tax_bracket == .35 %}selected{% endif %}>35% - Income $500,000/$600,000 Single/Married</option>
			  <option value=".37" {% if federal_tax_bracket == .37 %}selected{% endif %}>37% - Income $500,000+/$600,000+ Single/Married</option>
			</select>
			</div>
			<div class="col-md-12">
				<div class="collapse" id="price-collapse" name="federal_tax_bracket">
					<div class="card card-body">
						<p>Top marginal tax rate for your income - the higher your tax rate, the bigger the benefit of the mortgage interest and property tax deductions.</p>
					</div>
				</div>
			</div>
		</div>

		<div class="form-group row">
			<label for="id_state_tax_bracket" class="col-md-5 col-form-label">State tax rate</label>
			<div class="col-md-7">
				<div class="input-group">
					<input type="number" name="state_tax_bracket" min="0" max="100" step="0.01" class="form-control" required id="id_state_tax_bracket" value="6.0" />
					<div class="input-group-append">
						<span class="input-group-text">%</span>
					</div>
				</div>
			</div>
			<div class="col-md-12">
				<div class="collapse" id="price-collapse" name="state_tax_bracket">
					<div class="card card-body">
						<p>Top marginal state tax rate - the higher your tax rate, the bigger the benefit of the mortgage interest tax deduction.</p>
						<p>For reference: <a href="https://www.tax-brackets.org/">tax-brackets.org</a></p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-xs-12">
		<a class="btn btn-link" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
			Advanced options
		  </a>
	</div>
</div>
<div class="row">
	<div class="col-md-8">
		<div class="collapse" id="collapseExample">
			<div class="card card-body p-3 mb-2 bg-light text-dark">
				<div class="row">
					<div class="col-md-6">
						<div class="form-group row">
							<label for="id_closing_cost" class="col-md-5 col-form-label">Closing cost</label>
							<div class="col-md-7">
								<div class="input-group">
									<input type="number" name="closing_cost" min="0" max="100" step="0.01" class="form-control" required id="id_closing_cost" value="3.0" />
									<div class="input-group-append">
										<span class="input-group-text">%</span>
									</div>
								</div>
							</div>
							<div class="col-md-12">
								<div class="collapse" id="price-collapse" name="closing_cost">
									<div class="card card-body">
										<p>Closing costs (appraisals, loan origination fees, etc.) as a percent of the home price. This typically ranges 2-5%.</p>
									</div>
								</div>
							</div>
						</div>

						<div class="form-group row">
							<label for="id_property_tax" class="col-md-5 col-form-label">Property tax</label>
							<div class="col-md-7">
								<div class="input-group">
									<input type="number" name="property_tax" min="0" max="100" step="0.01" class="form-control" required id="id_property_tax" value="2.0" />
									<div class="input-group-append">
										<span class="input-group-text">%</span>
									</div>
								</div>
							</div>
							<div class="col-md-12">
								<div class="collapse" id="price-collapse" name="property_tax">
									<div class="card card-body">
										<p>Yearly property taxes as a percent of home price. This varies between state and municipality, but is typically 1-3% of the home value. </p>
									</div>
								</div>
							</div>
						</div>

						<div class="form-group row">
							<label for="id_insurance" class="col-md-5 col-form-label">Insurance</label>
							<div class="col-md-7">
								<div class="input-group">
									<input type="number" name="insurance" min="0" max="100" step="0.01" class="form-control" required id="id_insurance" value={% if insurance %}{{ insurance }}{% else %}1.0{% endif %} />
									<div class="input-group-append">
										<span class="input-group-text">%</span>
									</div>
								</div>
							</div>
							<div class="col-md-12">
								<div class="collapse" id="price-collapse" name="insurance">
									<div class="card card-body">
										<p>Yearly homeowner's insurance as a percent of home price. This varies depending on home location (e.g., flood prone, etc.).</p>
									</div>
								</div>
							</div>
						</div>
					</div>

					<div class="col-md-6">
						<div class="form-group row">
							<label for="id_maintenance_cost" class="col-md-5 col-form-label">Maintenance</label>
							<div class="col-md-7">
								<div class="input-group">
									<input type="number" name="maintenance_cost" min="0" max="100" step="0.01" class="form-control" required id="id_maintenance_cost" value="1.0" />
									<div class="input-group-append">
										<span class="input-group-text">%</span>
									</div>
								</div>
							</div>
							<div class="col-md-12">
								<div class="collapse" id="price-collapse" name="maintenance_cost">
									<div class="card card-body">
										<p>Yearly maintenance costs and upkeep (lawncare, plumbing, painting, etc.) per year as a percent of the home price. This is typically at least 1% of the home value.</p>
									</div>
								</div>
							</div>
						</div>

						<div class="form-group row">
							<label for="id_realtor_cost" class="col-md-5 col-form-label">Realtor cost</label>
							<div class="col-md-7">
								<div class="input-group">
									<input type="number" name="realtor_cost" min="0" max="100" step="0.01" class="form-control" required id="id_realtor_cost" value="6.0" />
									<div class="input-group-append">
										<span class="input-group-text">%</span>
									</div>
								</div>
							</div>
							<div class="col-md-12">
								<div class="collapse" id="price-collapse" name="realtor_cost">
									<div class="card card-body">
										<p>Percent of sale price paid to the listing agents by the seller. Typically 6%.</p>
									</div>
								</div>
							</div>
						</div>

						<div class="form-group row">
							<div class="col-md-12">
								<button class="btn btn-link" id="reset_defaults" type="button">Reset</button>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<div class="form-group row">
			<div class="col-md-12">
				<button type="submit" class="btn btn-info btn-lg" id="calculate">Calculate</button>
			</div>
		</div>
	</div>
</div>
	</form>

calc/templates/calc/stream-table.html
<table class="table-responsive table-sm">
	<thead id="thead" style="display:none;">
		<tr>
			<th scope="col">Year</th>
			<th scope="col">Principal Paid</th>
			<th scope="col">Interest Paid</th>
			<th scope="col">Other Costs</th>
			<th scope="col">Avoided Rent</th>
			<th scope="col">Net Spend</th>
			<th scope="col">Home Value</th>
			<th scope="col">Debt</th>
			<th scope="col">Equity</th>
			<th scope="col">IRR % (if sold)</th>
		</tr>
	</thead>
	<tbody id="tbody" name="tbody">

	</tbody>
</table>